#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

LETSENCRYPT_CRON="/etc/cron.d/openmediavault-acme"

case "$1" in
    purge)
        omv_config_delete "/config/services/acme"

        if [ -d "/root/.acme.sh" ]; then
            rm -rf "/root/.acme.sh"
        fi

        if [ -f "${LETSENCRYPT_CRON}" ]; then
            rm -f "${LETSENCRYPT_CRON}"
        fi
    ;;

    remove)
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
